language: python

python:
    - "3.6"

cache:
  pip:
  directories:
    - $TRAVIS_BUILD_DIR/.eggs
    - $TRAVIS_BUILD_DIR/.cache
    - $HOME/virtualenv

install:
  - pip install codecov

script:
  - python setup.py --quiet test

after_success:
  - codecov
